title: Geekcamp.SG
email: info@geekcamp.sg
description: >
  Geekcamp.SG website
baseurl: ""
url: "http://www.geekcamp.sg"
# Build settings
markdown: kramdown

exclude: ['Gemfile', 'Gemfile.lock', 'README.md', 'circle.yml', 'vendor']

page_gen:
  - data: 'talks'
    template: 'talk'
    dir: 'talks'
    name: 'slug'
    title: 'talk.title'
    description: 'talk.description'
