title: Geekcamp SG
email: info@geekcamp.sg
description: >
  Geekcamp SG website
baseurl: ""
url: "http://www.geekcamp.sg" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
